### ISSUE TITLE
Tesselating block (blockrootywater) resulting in crash Minecraft v. 1.12.2

### ISSUE THREAD

**Issue by DerangedLazyArtist** [the-realest-stu/DynamicTrees-BOP#105]
I can add the full crash report if necessary. I was able to duplicate this crash with versions 1.5.2 and 1.5.1 in two separate worlds.

// You're mean.

Time: 9/6/23 12:54 AM
Description: Tesselating block in world

java.lang.IllegalArgumentException: Cannot get property PropertyInteger{name=level, clazz=class java.lang.Integer, values=[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15]} as it does not exist in BlockStateContainer{block=minecraft:air, properties=[]}
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at git.jbredwards.fluidlogged_api.api.util.FluidState.getLevel(FluidState.java:130)
	at com.ferreusveritas.dynamictrees.blocks.BlockRootyWater.getExtendedState(BlockRootyWater.java:98)
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:79)
	at net.minecraft.client.renderer.chunk.RenderChunk.func_178581_b(RenderChunk.java:328)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.func_178474_a(SourceFile:100)
	at net.minecraft.client.renderer.chunk.ChunkRenderWorker.run(SourceFile:43)
	at java.lang.Thread.run(Thread.java:745)

No Mixin Metadata is found in the Stacktrace.

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at net.minecraft.block.state.BlockStateContainer$StateImplementation.func_177229_b(BlockStateContainer.java:209)
	at git.jbredwards.fluidlogged_api.api.util.FluidState.getLevel(FluidState.java:130)
	at com.ferreusveritas.dynamictrees.blocks.BlockRootyWater.getExtendedState(BlockRootyWater.java:98)

-- Block being tesselated --
Details:
	Block type: ID #930 (tile.dynamictreesbop:rootywater // com.ferreusveritas.dynamictrees.blocks.BlockRootyWater // dynamictreesbop:rootywater)
	Block data value: 0 / 0x0 / 0b0000
	Block location: World: (-1356,62,644), Chunk: (at 4,3,4 in -85,40; contains blocks -1360,0,640 to -1345,255,655), Region: (-3,1; contains chunks -96,32 to -65,63, blocks -1536,0,512 to -1025,255,1023)
Stacktrace:
	at net.minecraft.client.renderer.BlockRendererDispatcher.func_175018_a(BlockRendererDispatcher.java:79)

**Comment by supermassimo** [comment]
looks like an incompatibility with the fluidlogged api mod
