### ISSUE TITLE
Dark oak breaks instantaneously with 3.3.0 update.

### ISSUE THREAD

**Issue by kocane** [the-realest-stu/DynamicTrees-BOP#126]
After upgrading to 3.3.0 dark oak trees gets chopped down with one punch.

![issue](https://i.imgur.com/21hLmI4.gif)

Happens with both BOP 18 and BOP 19 along with DT 1.3.4 and the previous 1.3.3.

Not much to go by in the server logs other than this:
```
Warning: Tried to create a EntityFallingTree with no branch blocks. This shouldn't be possible.
java.lang.Exception
at TRANSFORMER/dynamictrees@1.20.1-1.3.4/com.ferreusveritas.dynamictrees.entity.FallingTreeEntity.setData(FallingTreeEntity.java:120)
at TRANSFORMER/dynamictrees@1.20.1-1.3.4/com.ferreusveritas.dynamictrees.entity.FallingTreeEntity.dropTree(FallingTreeEntity.java:536)
at TRANSFORMER/dynamictrees@1.20.1-1.3.4/com.ferreusveritas.dynamictrees.block.branch.BranchBlock.futureBreak(BranchBlock.java:526)
at TRANSFORMER/dynamictrees@1.20.1-1.3.4/com.ferreusveritas.dynamictrees.event.FutureBreak.process(FutureBreak.java:56)
at TRANSFORMER/dynamictrees@1.20.1-1.3.4/com.ferreusveritas.dynamictrees.event.handler.CommonEventHandler.onWorldTick(CommonEventHandler.java:20)
at TRANSFORMER/dynamictrees@1.20.1-1.3.4/com.ferreusveritas.dynamictrees.event.handler.__CommonEventHandler_onWorldTick_LevelTickEvent.invoke(.dynamic)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.ASMEventHandler.invoke(ASMEventHandler.java:73)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:315)
at MC-BOOTSTRAP/net.minecraftforge.eventbus/net.minecraftforge.eventbus.EventBus.post(EventBus.java:296)
at TRANSFORMER/forge@47.3.0/net.minecraftforge.event.ForgeEventFactory.onPreLevelTick(ForgeEventFactory.java:925)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5703_(MinecraftServer.java:890)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.dedicated.DedicatedServer.m_5703_(DedicatedServer.java:283)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_5705_(MinecraftServer.java:814)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_130011_(MinecraftServer.java:661)
at TRANSFORMER/minecraft@1.20.1/net.minecraft.server.MinecraftServer.m_206580_(MinecraftServer.java:251)
at java.base/java.lang.Thread.run(Unknown Source) 
```
Haven't experienced issue with any other trees.

**Comment by supermassimo** [comment]
Fixed in [3.3.1](https://www.curseforge.com/minecraft/mc-mods/dtbop/files/5939807)
