### ISSUE TITLE
1.16.5 Crash During create_registries Event Phase

### ISSUE THREAD

**Issue by ReginaBeahm** [the-realest-stu/DynamicTrees-BOP#65]
DynamicTreesBOP-1.16.5-2.0.4 crashes at startup as `therealeststu.dtbop.trees.MapleSpecies.getSeedName()` is not found. Here is the crash log:
```
---- Minecraft Crash Report ----
// Who set us up the TNT?

Time: 25/06/21 11:44
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.fml.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:85) [?:?] {re:classloading}
	at net.minecraftforge.fml.client.ClientModLoader.completeModLoading(ClientModLoader.java:188) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$null$1(Minecraft.java:508) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$9184/64697960.run(Unknown Source) [?:?] {}
	at net.minecraft.util.Util.func_215077_a(Util.java:430) [?:?] {re:classloading,xf:OptiFine:default,re:mixin}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:504) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft$$Lambda$8921/1932618250.accept(Unknown Source) [?:?] {}
	at net.minecraft.client.gui.ResourceLoadProgressGui.func_230430_a_(ResourceLoadProgressGui.java:172) [?:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.func_195458_a(GameRenderer.java:802) [?:?] {re:mixin,pl:accesstransformer:B,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:create.mixins.json:StoreProjectionMatrixMixin,pl:mixin:A}
	at net.minecraft.client.Minecraft.func_195542_b(Minecraft.java:976) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:607) [?:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:184) [?:?] {re:classloading,pl:runtimedistcleaner:A}
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_51] {}
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62) ~[?:1.8.0_51] {}
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:1.8.0_51] {}
	at java.lang.reflect.Method.invoke(Method.java:497) ~[?:1.8.0_51] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider.lambda$launchService$0(FMLClientLaunchProvider.java:51) [forge-1.16.5-36.1.0.jar:36.1] {}
	at net.minecraftforge.fml.loading.FMLClientLaunchProvider$$Lambda$490/2030707995.call(Unknown Source) [forge-1.16.5-36.1.0.jar:36.1] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:37) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:54) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:72) [modlauncher-8.0.9.jar:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:82) [modlauncher-8.0.9.jar:?] {re:classloading}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:66) [modlauncher-8.0.9.jar:?] {re:classloading}


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at therealeststu.dtbop.trees.MapleSpecies.generateSeed(MapleSpecies.java:21) ~[?:1.16.5-2.0.4] {re:classloading}
-- MOD dynamictrees --
Details:
	Caused by 0: java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: therealeststu.dtbop.trees.MapleSpecies.getSeedName()Lnet/minecraft/util/ResourceLocation;
		at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:659) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1587) ~[?:1.8.0_51] {}
		at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}

	Mod File: DynamicTrees-1.16.5-0.10.0-Beta16.jar
	Failure message: Dynamic Trees (dynamictrees) encountered an error during the create_registries event phase
		java.util.concurrent.CompletionException: java.lang.NoSuchMethodError: therealeststu.dtbop.trees.MapleSpecies.getSeedName()Lnet/minecraft/util/ResourceLocation;
	Mod Version: 1.16.5-0.10.0-Beta16
	Mod Issue URL: https://github.com/ferreusveritas/DynamicTrees/issues
	Exception message: java.lang.NoSuchMethodError: therealeststu.dtbop.trees.MapleSpecies.getSeedName()Lnet/minecraft/util/ResourceLocation;
Stacktrace:
	at therealeststu.dtbop.trees.MapleSpecies.generateSeed(MapleSpecies.java:21) ~[?:1.16.5-2.0.4] {re:classloading}
	at com.ferreusveritas.dynamictrees.trees.SpeciesManager.postLoad(SpeciesManager.java:114) ~[?:1.16.5-0.10.0-Beta16] {re:classloading}
	at com.ferreusveritas.dynamictrees.trees.SpeciesManager.postLoad(SpeciesManager.java:34) ~[?:1.16.5-0.10.0-Beta16] {re:classloading}
	at com.ferreusveritas.dynamictrees.resources.JsonRegistryEntryReloadListener.lambda$apply$2(JsonRegistryEntryReloadListener.java:99) ~[?:1.16.5-0.10.0-Beta16] {re:classloading}
	at com.ferreusveritas.dynamictrees.resources.JsonRegistryEntryReloadListener$$Lambda$8582/1684375837.accept(Unknown Source) ~[?:?] {}
	at java.util.LinkedHashMap.forEach(LinkedHashMap.java:676) ~[?:1.8.0_51] {}
	at com.ferreusveritas.dynamictrees.resources.JsonRegistryEntryReloadListener.apply(JsonRegistryEntryReloadListener.java:46) ~[?:1.16.5-0.10.0-Beta16] {re:classloading}
	at com.ferreusveritas.dynamictrees.resources.JsonRegistryEntryReloadListener.apply(JsonRegistryEntryReloadListener.java:22) ~[?:1.16.5-0.10.0-Beta16] {re:classloading}
	at com.ferreusveritas.dynamictrees.resources.ReloadListener.lambda$load$1(ReloadListener.java:40) ~[?:1.16.5-0.10.0-Beta16] {re:classloading}
	at com.ferreusveritas.dynamictrees.resources.ReloadListener$$Lambda$8558/952833542.accept(Unknown Source) ~[?:?] {}
	at java.util.concurrent.CompletableFuture.uniAccept(CompletableFuture.java:656) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$UniAccept.tryFire(CompletableFuture.java:632) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture.postComplete(CompletableFuture.java:474) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1587) ~[?:1.8.0_51] {}
	at java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1574) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) ~[?:1.8.0_51] {}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1689) ~[?:1.8.0_51] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) ~[?:1.8.0_51] {}
```

**Comment by ReginaBeahm** [comment]
My bad I just needed to update Dynamic Trees from Beta16 to Beta17
