### ISSUE TITLE
Exception Crash: Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0

### ISSUE THREAD

**Issue by wadiv76** [the-realest-stu/DynamicTrees-BOP#88]
Minecraft Version: 1.18.2
DynamicTrees-BOP version [DynamicTreesBOP-1.18.2-3.0.0-ALPHA1.jar]

In therealeststu.dtbop.genfeature.AlternativeLeavesGenFeature.postGenerate(AlternativeLeavesGenFeature.java:51) the PostGenerationContext is requesting a Bounds index 0 of a length 0 array.  

It appeared to be within a Mystical Forest if that helps

Crash log:
`
Caused by: java.lang.IndexOutOfBoundsException: Index 0 out of bounds for length 0
	at java.base/jdk.internal.util.Preconditions.outOfBounds(Preconditions.java:64)
	at java.base/jdk.internal.util.Preconditions.outOfBoundsCheckIndex(Preconditions.java:70)
	at java.base/jdk.internal.util.Preconditions.checkIndex(Preconditions.java:266)
	at java.base/java.util.Objects.checkIndex(Objects.java:359)
	at java.base/java.util.ArrayList.get(ArrayList.java:427)
	at TRANSFORMER/dynamictrees@1.18.2-0.11.0-Alpha2/com.ferreusveritas.dynamictrees.util.BlockBounds.<init>(BlockBounds.java:68)
	at TRANSFORMER/dtbop@1.18.2-3.0.0-ALPHA1/therealeststu.dtbop.genfeature.AlternativeLeavesGenFeature.postGenerate(AlternativeLeavesGenFeature.java:51)
	at TRANSFORMER/dynamictrees@1.18.2-0.11.0-Alpha2/com.ferreusveritas.dynamictrees.systems.genfeatures.GenFeature$Type.generate(GenFeature.java:196)
	at TRANSFORMER/dynamictrees@1.18.2-0.11.0-Alpha2/com.ferreusveritas.dynamictrees.systems.genfeatures.GenFeature.generate(GenFeature.java:105)
	at TRANSFORMER/dynamictrees@1.18.2-0.11.0-Alpha2/com.ferreusveritas.dynamictrees.systems.genfeatures.GenFeatureConfiguration.generate(GenFeatureConfiguration.java:50)
	at TRANSFORMER/dynamictrees@1.18.2-0.11.0-Alpha2/com.ferreusveritas.dynamictrees.trees.Species.lambda$postGeneration$16(Species.java:2062)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/dynamictrees@1.18.2-0.11.0-Alpha2/com.ferreusveritas.dynamictrees.trees.Species.postGeneration(Species.java:2061)
	at TRANSFORMER/dynamictrees@1.18.2-0.11.0-Alpha2/com.ferreusveritas.dynamictrees.worldgen.JoCode.generate(JoCode.java:246)
	at TRANSFORMER/dynamictrees@1.18.2-0.11.0-Alpha2/com.ferreusveritas.dynamictrees.trees.Species.generate(Species.java:1975)
	at TRANSFORMER/dynamictrees@1.18.2-0.11.0-Alpha2/com.ferreusveritas.dynamictrees.worldgen.TreeGenerator.makeTree(TreeGenerator.java:139)
	at TRANSFORMER/dynamictrees@1.18.2-0.11.0-Alpha2/com.ferreusveritas.dynamictrees.worldgen.TreeGenerator.makeTrees(TreeGenerator.java:103)
	at TRANSFORMER/dynamictrees@1.18.2-0.11.0-Alpha2/com.ferreusveritas.dynamictrees.worldgen.DynamicTreeFeature.lambda$place$0(DynamicTreeFeature.java:48)
	at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
	at TRANSFORMER/dynamictrees@1.18.2-0.11.0-Alpha2/com.ferreusveritas.dynamictrees.worldgen.DynamicTreeFeature.m_142674_(DynamicTreeFeature.java:48)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.feature.Feature.m_204740_(Feature.java:153)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.feature.ConfiguredFeature.m_65385_(ConfiguredFeature.java:27)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191789_(PlacedFeature.java:56)
	at java.base/java.util.stream.Streams$StreamBuilderImpl.forEachRemaining(Streams.java:411)
	at java.base/java.util.stream.ReferencePipeline$Head.forEach(ReferencePipeline.java:762)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191797_(PlacedFeature.java:55)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.levelgen.placement.PlacedFeature.m_191806_(PlacedFeature.java:44)
	at TRANSFORMER/terraforged@0.3.1/com.terraforged.mod.worldgen.cave.NoiseCaveDecorator.decorate(NoiseCaveDecorator.java:72)
	at TRANSFORMER/terraforged@0.3.1/com.terraforged.mod.worldgen.cave.NoiseCaveDecorator.decorate(NoiseCaveDecorator.java:51)
	at TRANSFORMER/terraforged@0.3.1/com.terraforged.mod.worldgen.cave.NoiseCaveGenerator.decorate(NoiseCaveGenerator.java:84)
	at TRANSFORMER/terraforged@0.3.1/com.terraforged.mod.worldgen.biome.BiomeGenerator.decorate(BiomeGenerator.java:78)
	at TRANSFORMER/terraforged@0.3.1/com.terraforged.mod.worldgen.Generator.m_183372_(Generator.java:208)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkStatus.m_187807_(ChunkStatus.java:135)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.world.level.chunk.ChunkStatus.m_187788_(ChunkStatus.java:262)
	at TRANSFORMER/minecraft@1.18.2/net.minecraft.server.level.ChunkMap.lambda$scheduleChunkGeneration$22(ChunkMap.java:589)
	... 14 more`

**Comment by supermassimo** [comment]
Please try this patch and let me know if you are still having the issue https://legacy.curseforge.com/minecraft/mc-mods/dtbop/files/4535955

**Comment by Harleyoc1** [comment]
I'm going to assume this fixed. If you encounter the issue on the latest version let us know.
